### ISSUE TITLE
[BUG] Stops registry editing.

### ISSUE THREAD

**Issue by jonathanafranio** [ComfortablyCoding/strapi-plugin-publisher#134] opened 2024-01-10 18:55 UTC
When testing the plugin with a robust database, when editing the registry, the page kept crashing the browser.
When removed, operation returned to normal.
![image](https://github.com/ComfortablyCoding/strapi-plugin-publisher/assets/768332/96ec52cd-4c25-4142-898a-dc8442235a30)
Strapi version: v4.10.2
Node Version: v18.19

**Comment by ComfortablyCoding** [comment] 2024-01-17 04:41
Only the latest version is fully supported, I cannot reproduce this with simply changing input values and saving. Possible related to #135 . Closing for now, happy to re-open if reproducible steps on the latest version are provided.

**Closed by ComfortablyCoding** 2024-01-17 04:41 UTC
