### ISSUE TITLE
Not Respecting 24hr Time

### ISSUE THREAD

**Issue by TasosBak** [ComfortablyCoding/strapi-plugin-publisher#121] opened 2023-11-01 02:02 UTC
Even though in the select button you can select a time according to 24hr clock it behaves like it is a 12hr without a way to set AM/PM. 

Regardless of whether I set a time for an action to occur (e.g., 02:00 or 14:00), the action will execute at both 02:00 AND 14:00 (in this example). 

```
"@strapi/strapi": "4.14.0",
"strapi-plugin-publisher": "^1.5.0",
```

**Comment by ComfortablyCoding** [comment] 2023-11-01 17:48
Thanks for the report, I will see if I can  reproduce this.

**Comment by ComfortablyCoding** [comment] 2023-11-02 12:43
I cannot reproduce this issue.

A publish date of 20:00 does not execute at 8:00 for me.

In terms of 2:00 executing at 14:00 it depends on your cron frequency but this is somewhat normal/expected. 

The action will trigger at any time after the time set. So for example if you set it for 2:00 and have the cron run at 2:00 and 14:00, any actions that was set any time between 2:00 and 14:00 will execute at 14:00.

The published_at should still show whatever time it was set for even if it publishes later.

Closing as this is not an issue.

**Closed** 2023-11-02 12:43 UTC
