### ISSUE TITLE
Error loading the plugin after updating Strapi to version 4.17.1

### ISSUE THREAD

**Issue by AliKdhim87** [ComfortablyCoding/strapi-plugin-publisher#138] opened 2024-01-19 15:07 UTC
# Error loading the plugin after updating Strapi to version 4.17.1

## Description:

After updating Strapi to version 4.17.1, I encountered the following error when trying to use the `strapi-plugin-publisher`:

## Environment

- Plugin Version: 1.5.7
- Strapi Version: 4.17.1
- Node.js Version: 20.10.0
- Operating System: macOS
- yarn: 1.22.19

## Steps to Reproduce:

1. Install `strapi-plugin-publisher` version 1.5.7.
2. Update Strapi to version 4.17.1.
3. Start Strapi and observe the error.

## Error Message

```shell
Error: Error loading the plugin publisher because publisher is not installed. Please either install the plugin or remove it's   ││   configuration.                                                                                                                  ││   at Object.loadPlugins                                                                                                        ││   at Object.loadPlugins 
```

**Comment by ComfortablyCoding** [comment] 2024-01-21 20:32
I am unable to reproduce this issue with the steps provided. This issue is most likely due to your specific setup as opposed to his plugin. Closing this issue for now, happy to re-open if this turns out to not be the case.

**Closed by ComfortablyCoding** 2024-01-21 20:32 UTC
