### ISSUE TITLE
entry.publish missing some data's while triggering the webhook from strapi

### ISSUE THREAD

**Issue by maruthasalamr** [ComfortablyCoding/strapi-plugin-publisher#55] opened 2023-02-27 17:23 UTC
When i publish the contents through strapi plugin publisher some data's are missing when webhook is triggred.If i publish the same content manually means i can able to get all the data.

**Comment by ComfortablyCoding** [comment] 2023-02-28 03:17
Duplicate of #51

**Closed** 2023-02-28 03:17 UTC
