### ISSUE TITLE
Publishing every time

### ISSUE THREAD

**Issue by GautierDele** [ComfortablyCoding/strapi-plugin-publisher#15] opened 2022-03-02 19:39 UTC
On a linux server, it seems like the plugin is publishing not relating on the date. Even if I put a date that is far in time to publish:
![image](https://user-images.githubusercontent.com/12382966/156436247-0ac222d8-a05b-46b7-a457-98c47778fc22.png)
![image](https://user-images.githubusercontent.com/12382966/156437087-4acc7018-be72-47b9-8685-c27ca0d90648.png)
When the cron action gets launched, the entry get published not considering the date.
![image](https://user-images.githubusercontent.com/12382966/156437294-7742901f-3a21-4a91-aa57-fbaf75894403.png)

I checked dates and they seem great:
![image](https://user-images.githubusercontent.com/12382966/156436141-0b09a55c-b517-4d02-b392-d820d224ded3.png)

**Comment by ComfortablyCoding** [comment] 2022-03-02 20:05
What version of strapi and the plugin are you running?

**Comment by GautierDele** [comment] 2022-03-02 21:11
Strapi 4.1.1
Plugin 1.1.2

**Comment by ComfortablyCoding** [comment] 2022-03-03 06:33
The last fully tested version was 4.0.7, it looks like they changed how dates work in 4.0.8+ which is the cause of this. I will look into releasing a fix for this.

From my testing for this issue it looks like on 4.1.2 the filtering seems to be broken completely. It is not a plugin issue as it works fine in previous strapi versions. I will need to investigate this further to see if i can find the changes that cause it.

**Comment by GautierDele** [comment] 2022-03-03 12:49
I'm on it, will publish a PR when fixed with french localizations

**Closed** 2022-03-04 03:39 UTC
Labels: bug

**Comment by neilpoulin** [comment] 2022-03-17 23:04
this is not working for me still, it seems like ever time the minute changes that any schedueld action is fired - publishing or unpublishing. 

I'm using: 
strapi `4.1.5`
strapi-plugin-publisher: `1.1.3`

**Comment by ComfortablyCoding** [comment] 2022-03-25 03:32
Its possible something changed again between 4.1.2 -> 4.1.5. I will investigate this further and see if I can reproduce the issue.

**Comment by GautierDele** [comment] 2022-03-25 08:01
Working fine on my side. Did you publish your project ?
```sh
npm run build
```
